name: makepkg

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 0 * * *'

jobs:

  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
        fetch-depth: 0
    - name: set up environments
      run: |
        mkdir -p .ssh
        echo ${{secrets.zasdfgbnm_bot_public_key}} > .ssh/id_rsa.pub
        echo ${{secrets.zasdfgbnm_bot_private_key}} | base64 -d > .ssh/id_rsa
    - name: build
      run: |
        set -eux
        docker pull zasdfgbnm/archlinux-yaourt
        sudo docker run --privileged -v $PWD:/w -w /w zasdfgbnm/archlinux-yaourt bash -c '
          set -eux
          ./install-deps.sh
          ./build-packages.xsh
        '
