name: makepkg

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up environments
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
        git config --global user.email "zasdfgbnm-bot@example.com"
        git config --global user.name "zasdfgbnm-bot"
    - name: build
      run: docker run zasdfgbnm/archlinux-yaourt -v $HOME:/home/user -v $PWD:/workspace /workspace/build-packages.sh
